@host= http://localhost:3000/dev
POST {{host}}/songs
Content-Type: application/json

{
    "name": "AWS23112",
    "artist": "AB23",
    "duration": 182,
    "album": "Fantastic3",
    "genre": "pop"
}

###

GET {{host}}/songs